#!/bin/bash

# starting daemons
sxhkd &
pipewire &
eww open topbar

# wallpaper
rm /tmp/xlivebg.sock
xlivebg -n &

# suppress the Wine system tray, we don't need it around these parts
trayer --width 0 &

# stuff
xsetroot -cursor_name right_ptr
picom --config ~/.config/picom/picom.conf --experimental-backends &
./floating_picom_shadows.sh
$HOME/.screenlayout/main-4k.sh

# config bspwm
bspc config border_width 0
bspc config window_gap 0
# bspc config top_padding 22
bspc config split_ratio 0.5
bspc config focus_follows_pointer true

feh --bg-fill ~/Pictures/TokyoNightWall.png &

bspc config automatic_scheme longest_side
bspc config pointer_follows_focus true

# monitor workspaces
bspc monitor DP-2 -d 0 1 2 3 4 5 6 7 8 9 
bspc monitor DP-4 -d 0 1 2 3 4 5 6 7 8 9

bspc config normal_border_color "#ffcda9"
bspc config active_border_color "#ffc089"
bspc config focused_border_color "#ff5076"
bspc config presel_feedback_color "#2a1362"
# ./dynamic_border_width.sh &

# bspc wm -r
